### PR TITLE
Update cargo lock file

### PR DESCRIPTION
**Pull request by zainkabani**
Major change being updating tokio to latest version to [1.24](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.24.0) which has CPU performance improvements

### CODE REVIEW

**Comment by levkk** [comment]
Dependabot should take care of this I think pretty soon?

**Comment by levkk** [comment]
But you're faster, so let's do this!

**Comment by zainkabani** [comment]
I think it hasn't been picked up yet because of how the cargo.toml defines tokio. It's not a specific version

**Comment by levkk** [comment]
Huh well it should be able to upgrade freely then

**Pull request merged**
